# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.

orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs

jobs:
  configure_infrastructure:
    docker:
      - image: python:3.9-alpine
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "62:59:63:84:5d:e2:22:f0:27:d7:2e:25:3b:a0:10:91"
      - run:
          name: Install dependencies
          command: |
            pip install pip --upgrade
            pip install ansible
            apk update
            apk add --virtual build-dependencies   
      - run:
          name: Configure server
          command: |
            export ANSIBLE_HOST_KEY_CHECKING=False   
            ansible-playbook -i inventory.txt main-playbook.yml


workflows:
  my_workflow:
    jobs:
      - configure_infrastructure