# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
commands:
  print_pipeline_id:
    description: "A very simple command"
    to:
      type: string
      default: "hello"
    steps:
      - run: echo << parameters.to >>
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs

jobs:
  test-print:
    docker:
      - image: "circleci/node:9.6.1"
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - print_pipeline_id:
          to: "$CIRCLE_WORKFLOW_ID"
      
workflows:
  default:
    jobs:
      - test-print